name: Upload Website
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build --if-present
      - run: npm test
        env:
          CI: true

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Setup AWS CLI
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Custom step to upload files with specific MIME types
      - name: Upload files to S3 with correct MIME types
        run: |
          aws s3 cp ./build s3://${{ secrets.AWS_S3_BUCKET }} --recursive --acl public-read --content-type "text/javascript" --exclude "*" --include "*.js"
          aws s3 cp ./build s3://${{ secrets.AWS_S3_BUCKET }} --recursive --acl public-read --exclude "*.js"
