name: Upload Website
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm install
      - run: npm run build --if-present
      - run: npm test
        env:
          CI: true

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Setup AWS CLI
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Upload files to S3 with correct MIME types
      - name: Upload HTML files to S3
        run: |
          aws s3 cp ./build s3://${{ secrets.AWS_S3_BUCKET }} --recursive --acl public-read --exclude "*" --include "*.html" --content-type "text/html"
          aws s3 cp ./build s3://${{ secrets.AWS_S3_BUCKET }} --recursive --acl public-read --exclude "*" --include "*.js" --content-type "text/javascript"
          aws s3 cp ./build s3://${{ secrets.AWS_S3_BUCKET }} --recursive --acl public-read --exclude "*" --include "*.css" --content-type "text/css"
          aws s3 cp ./build s3://${{ secrets.AWS_S3_BUCKET }} --recursive --acl public-read --exclude "*.html" --exclude "*.js" --exclude "*.css"
